language: node_js
node_js:
- 6
branches:
  only:
  - master
  - "/v\\d+\\.\\d+\\.\\d+(-\\w+)?/"
script: "./test.sh"
jobs:
  include:
  - stage: release
    script: skip
    deploy:
      provider: npm
      email: kossnocorp@gmail.com
      api_key:
        secure: N5Q3FGcCzBa/S250IscloRbwdtbiZhO6bg6BwyL8AuoyFIKOh6PLvFs+lDKlUhlTMFAiSRM0bdRl8r7qwzVRaBT/OKKdlVKS3zdGlr/RsJBUYyoG2fdM5Zjw2r7rJJboSszYwfptA1EX4xKaHCvmjIXIODwG5PuGY1cjmF6d5tGlGm2uU6uB4Gg7xXMWGpDeTE8KZhLaeCw12CmYv9sA8gzfqqtrpNLEwmpPho3sYptloqz3Xv2z1Qwa9HtWxbjV4DXChKjPz45bMFvRzVI3CZV5vxscTrRHceAwjVkV+LYM4maHfn08bh3G+sdBFXylMtX3RkRlRqu6Er596zEgTdAQuxcvkyrfFi7+5uJNRF49tvbplyx0NpsoRPXgc1ZZNo3D08QklOI/ztHpi2DiQXGvc17v2YL/jZlPwsvtXRZtpGqKDp/Yu32PnloboIbWRJ61s0jLcUxMRKhSyXti86FWsKSjN8KdQpZ5TvWeFSdfDvX8T4twWAc1bbtmBIczpU6YKvveAQW///X/kXE/8FwDy8QrC29Fndd3eNGp+uuW+VtJeJsxgIGGN7fij7kHL3p/zoncKRUsO6cKth9qJpvmg0u+VY4mYNLDu3VGIBFVJdnf4g/NWBT3xrvG5CDRg+Hm1kIRSxCiE+Ql5ffEv3BRLbJRvd0siJfld+jgNec=
      on:
        tags: true
before_deploy:
- "./writeVersion.js"
